### PR TITLE
Delete Visa and Mastercard "drawable" image.

### PR DESCRIPTION
**Pull request by javichaques**
Update Grardle, SDK and libraries.
Delete different Visa and Mastercad image

### CODE REVIEW

**Comment by javichaques** [comment]
I updated the PR with stable version and deleted iml

**Comment by vinaygaba** [comment]
The TravisCi build is failing for your PR. That's because you will also have to bump up the sdk version in the .travis.yml file.
Update this value - https://github.com/vinaygaba/CreditCardView/blob/master/.travis.yml#L19

**Comment by javichaques** [comment]
I updated .gitginore and travis.yml

**Comment by vinaygaba** [comment]
Thank you!

**Pull request merged**
