### PR TITLE
Completing issue "Change the package name to com.vinaygaba.creditcardview"

### PR DESCRIPTION
**Pull request by GregSaintJean**
Changed the package name to com.vinaygaba.creditcardview.
Added more files to .gitignore.
Updated gradle version.
DId some cleanup.

### CODE REVIEW

**Comment by vinaygaba** [comment]
Great work Greg! Just one request, would it be possible to change it to com.vinaygaba.creditcardview instead of com.vinaygaba.creditcardview.library? I tried making this change yesterday but faced some trouble in doing so.

**Comment by GregSaintJean** [comment]
Sure thing! I'll get right on it.

**Comment by GregSaintJean** [comment]
Resolve #1.

**Comment by vinaygaba** [comment]
Awesome work Greg! Will be merging it as soon as I upload the next release to maven to avoid confusion. Wanted to know your opinion about how I should be managing the releases?

**Comment by GregSaintJean** [comment]
Is there something specific you wanted to know or do you want general advice?

**Comment by GregSaintJean** [comment]
I won't know.I don't contribute enough to know anything really. The only thing I see people do is use tags.

**Pull request merged**
